container.opt<-c()
test.error.rf.def.corr00.sim<-c()
test.error.rf.opt.corr00.sim<-c()
test.error.rf.rfe.def.corr00.sim<-c()
test.error.rf.def.corr03.sim<-c()
test.error.rf.opt.corr03.sim<-c()
test.error.rf.rfe.def.corr03.sim<-c()
test.error.rf.def.corr06.sim<-c()
test.error.rf.opt.corr06.sim<-c()
test.error.rf.rfe.def.corr06.sim<-c()
test.error.rf.def.corr09.sim<-c()
test.error.rf.opt.corr09.sim<-c()
test.error.rf.rfe.def.corr09.sim<-c()
average.rf.def.corr00.sim<-c()
average.rf.opt.corr00.sim<-c()
average.rf.rfe.def.corr00.sim <- c()
average.rf.def.corr03.sim <- c()
average.rf.opt.corr03.sim <- c()
average.rf.rfe.def.corr03.sim <- c()
average.rf.def.corr06.sim <- c()
average.rf.opt.corr06.sim <- c()
average.rf.rfe.def.corr06.sim <- c()
average.rf.def.corr09.sim <- c()
average.rf.opt.corr09.sim <- c()
average.rf.rfe.def.corr09.sim <- c()
length.X.corr00<-c()
length.X.corr03<-c()
length.X.corr06<-c()
length.X.corr09<-c()

