container.opt<-c()
container.opt.N100<-c()
container.opt.N500<-c()
test.error.rf.def.sim<-c()
test.error.rf.opt.sim<-c()
test.error.rf.rfe.def.sim<-c()
test.error.rf.def.N100.sim<-c()
test.error.rf.opt.N100.sim<-c()
test.error.rf.rfe.def.N100.sim<-c()
test.error.rf.def.N500.sim<-c()
test.error.rf.opt.N500.sim<-c()
test.error.rf.opt.N500.sim<-c()
test.error.rf.rfe.def.N500.sim<-c()
average.rf.def.sim<-c()
average.rf.opt.sim<-c()
average.rf.rfe.def.sim <- c()
average.rf.def.N100.sim <- c()
average.rf.opt.N100.sim <- c()
average.rf.rfe.def.N100.sim <- c()
average.rf.def.N500.sim <- c()
average.rf.opt.N500.sim <- c()
average.rf.rfe.def.N500.sim <- c()
length.X<-c()
length.X.N100<-c()
length.X.N500<-c()